# Generated by Django 5.1.3 on 2024-11-26 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_message_content_remove_message_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
